name: Build test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cmake ${{ github.workspace }}

      - name: Compile
        run: make -j$(nproc)

      - name: Run
        run: ./calcplusplus
