name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create build dir
        run: mkdir build/

      - name: Go to build dir
        run: cd build/

      - name: Build
        run: cmake ${{github.workspace}}/

      - name: Compile
        run: make -j$(nproc)
